language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
before_script: composer install --prefer-source
script: phpunit --configuration phpunit.xml.dist
cache:
  directories:
    - vendor
matrix:
  allow_failures:
    - php: hhvm
